---
name: Vuelta 2022
status: closed
start: 2022-08-19
maxCyclistsInUserTeam: 12
jerseys:
  De Rode Trui: 10
  De Bolletjes Trui: 5
scoring:
  - 30
  - 15
  - 12
  - 9
  - 5
  - 4
  - 3
  - 2
  - 1
